/**
 * @file Version.h
 * @brief Version information for the Orpheus Audio Engine.
 *
 * This file is auto-generated by CMake from Version.h.in.
 * Do not edit directly.
 */
#pragma once

/// Major version number
#define ORPHEUS_VERSION_MAJOR 1

/// Minor version number
#define ORPHEUS_VERSION_MINOR 0

/// Patch version number
#define ORPHEUS_VERSION_PATCH 0

/// Full version string (e.g., "1.0.0")
#define ORPHEUS_VERSION_STRING "1.0.0"

/// Version as a single integer (MAJOR * 10000 + MINOR * 100 + PATCH)
#define ORPHEUS_VERSION_NUMBER                                                 \
  (ORPHEUS_VERSION_MAJOR * 10000 + ORPHEUS_VERSION_MINOR * 100 +               \
   ORPHEUS_VERSION_PATCH)

/**
 * @brief Check if the current version is at least the specified version.
 * @param major Required major version.
 * @param minor Required minor version.
 * @param patch Required patch version.
 * @return true if current version >= required version.
 */
#define ORPHEUS_VERSION_AT_LEAST(major, minor, patch)                          \
  (ORPHEUS_VERSION_NUMBER >= ((major) * 10000 + (minor) * 100 + (patch)))

namespace Orpheus {

/// Major version
constexpr int VersionMajor = ORPHEUS_VERSION_MAJOR;

/// Minor version
constexpr int VersionMinor = ORPHEUS_VERSION_MINOR;

/// Patch version
constexpr int VersionPatch = ORPHEUS_VERSION_PATCH;

/// Full version string
constexpr const char *VersionString = ORPHEUS_VERSION_STRING;

} // namespace Orpheus
